### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by rutvikpensionwar** [AfterShip/aftership-sdk-python#15]
It seems the latest release to this package is unstable.

![image](https://user-images.githubusercontent.com/18364112/76257856-b8a3de80-620f-11ea-9f67-fe1ebaac2555.png)

Let me know if I am doing something wrong.

**Comment by rutvikpensionwar** [comment]
@alviezhang Let me know if you could help.

**Comment by alviezhang** [comment]
Thanks for your feedback, fixed in #16.
