### ISSUE TITLE
Attribute error :'module' object has no attribute 'tracking'

### ISSUE THREAD

**Issue by amitlimbaskar** [AfterShip/aftership-sdk-python#20]
When I run Aftership_tracking_example.py with updated API key and tracking number , I receive the following error
: Attribute error :'module' object has no attribute 'tracking' . I have downloaded and installed Aftership module using pip. I also see tracking.py in that module. Could you please help me with this issue ?

**Comment by alviezhang** [comment]
Which version of Python and SDK version are you using?

**Comment by amitlimbaskar** [comment]
Python version 3.8 , SDK is same as here. Aftership module :1.0 ( latest version installed by pip)

**Comment by alviezhang** [comment]
We have a post-release named `1.0.post2`, it fixed import error. However, people often confused about this. So we released the `1.1.0` which works fine, please try this version of SDK.

**Comment by amitlimbaskar** [comment]
Hi, this new version of Aftership worked for importing tracking module. However it is erroring out with Bad_request: tracking already exists. I'm using tid = create_tracking('ups', '1Z4X8V060316994788').

**Comment by alviezhang** [comment]
Obviously you already created a tracking with same slug and tracking number in your account.
You can call `trackin.get_tracking(slug='ups', tracking_number='1Z4X8V060316994788')` to check your exist tracking information.

**Comment by alviezhang** [comment]
I'll close this ticket since the original question is resolved. Welcome to file new ticket if you has other questions.
